"""Argument schemas for the appointment tools.

These are the trust boundary. Everything here arrives as JSON generated by an
LLM from a caller's speech — two untrusted hops, not one. ``extra="forbid"``
matters: it turns an invented argument into a rejection instead of a silent
no-op, which is the difference between noticing an injection attempt and not.
"""

from __future__ import annotations

import datetime as _dt
import re

from pydantic import BaseModel, ConfigDict, Field, field_validator

# Deliberately permissive about formatting, strict about content: a caller may
# say "seven five four, two zero three..." and the LLM may render it any number
# of ways, but it must still resolve to 10-15 digits.
_PHONE_DIGITS = re.compile(r"\d")
_MIN_PHONE_DIGITS = 10
_MAX_PHONE_DIGITS = 15


class _Strict(BaseModel):
    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)


def _normalize_phone(value: str) -> str:
    digits = "".join(_PHONE_DIGITS.findall(value))
    if not _MIN_PHONE_DIGITS <= len(digits) <= _MAX_PHONE_DIGITS:
        raise ValueError("phone must contain 10 to 15 digits")
    return f"+{digits}" if value.strip().startswith("+") else digits


class CheckAvailabilityArgs(_Strict):
    """Look up open appointment slots on one calendar day."""

    date: _dt.date = Field(description="Calendar day to check, ISO 8601 (YYYY-MM-DD).")


class BookAppointmentArgs(_Strict):
    """Reserve one specific slot for one caller."""

    slot_id: str = Field(
        min_length=10,
        max_length=32,
        description="Slot identifier exactly as returned by check_availability.",
    )
    caller_name: str = Field(min_length=1, max_length=80)
    phone: str = Field(min_length=7, max_length=32)
    email: str | None = Field(default=None, max_length=120)
    reason: str | None = Field(default=None, max_length=240)

    @field_validator("phone")
    @classmethod
    def _phone(cls, value: str) -> str:
        return _normalize_phone(value)

    @field_validator("email")
    @classmethod
    def _email(cls, value: str | None) -> str | None:
        if value is None:
            return None
        if "@" not in value or value.startswith("@") or value.endswith("@"):
            raise ValueError("email is not a valid address")
        return value.lower()


class CaptureLeadArgs(_Strict):
    """Record a caller who is not booking right now."""

    caller_name: str = Field(min_length=1, max_length=80)
    phone: str = Field(min_length=7, max_length=32)
    email: str | None = Field(default=None, max_length=120)
    interest: str | None = Field(default=None, max_length=240)
    notes: str | None = Field(default=None, max_length=500)

    @field_validator("phone")
    @classmethod
    def _phone(cls, value: str) -> str:
        return _normalize_phone(value)
